// src/lib/reports/prisonerReport.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generate a comprehensive prisoner report
 * @param {Object} prisoner - Prisoner data
 * @param {Object} options - Report options
 * @param {Array} options.workRecords - Work records if available
 * @param {Object} options.workSummary - Work summary if available
 * @param {Array} options.behaviorRecords - Behavior records if available
 * @param {Object} options.behaviorSummary - Behavior summary if available
 * @param {Array} options.visits - Visit records if available
 * @param {Object} options.visitsSummary - Visits summary if available
 * @param {Object} options.generatedBy - User who generated the report
 */
export const generatePrisonerReport = (prisoner, options = {}) => {
  const {
    workRecords = [],
    workSummary = null,
    behaviorRecords = [],
    behaviorSummary = null,
    visits = [],
    visitsSummary = null,
    generatedBy = null,
  } = options;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = 20;

  // Helper functions
  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const formatTime = (timeString) => {
    if (!timeString) return 'N/A';
    const [hours, minutes] = timeString.split(':');
    const hour = parseInt(hours);
    const ampm = hour >= 12 ? 'PM' : 'AM';
    const displayHour = hour % 12 || 12;
    return `${displayHour}:${minutes} ${ampm}`;
  };

  const formatCurrency = (amount) => {
    return `Rs. ${parseFloat(amount).toLocaleString('en-US', {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    })}`;
  };

  const calculateAge = (birthday) => {
    const today = new Date();
    const birthDate = new Date(birthday);
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age;
  };

  const addHeader = () => {
    // Header
    doc.setFillColor(30, 41, 59); // slate-800
    doc.rect(0, 0, pageWidth, 35, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('PRISONER INFORMATION REPORT', pageWidth / 2, 15, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Confidential Document', pageWidth / 2, 25, { align: 'center' });
    
    yPosition = 45;
  };

  const addFooter = (pageNumber) => {
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      `Page ${pageNumber} | Generated on ${formatDate(new Date())}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    
    if (generatedBy) {
      doc.text(
        `Generated by: ${generatedBy.fullName}`,
        margin,
        pageHeight - 10
      );
    }
  };

  const checkPageBreak = (requiredSpace) => {
    if (yPosition + requiredSpace > pageHeight - 30) {
      doc.addPage();
      addHeader();
      addFooter(doc.internal.getNumberOfPages());
      return true;
    }
    return false;
  };

  const addSectionTitle = (title) => {
    checkPageBreak(20);
    doc.setFillColor(241, 245, 249); // slate-100
    doc.rect(margin, yPosition, pageWidth - (2 * margin), 10, 'F');
    
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(title, margin + 3, yPosition + 7);
    
    yPosition += 15;
  };

  const addField = (label, value, inline = false) => {
    checkPageBreak(10);
    doc.setFontSize(9);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(71, 85, 105); // slate-600
    
    if (inline) {
      doc.text(`${label}:`, margin, yPosition);
      doc.setFont(undefined, 'normal');
      doc.setTextColor(15, 23, 42);
      doc.text(String(value), margin + 40, yPosition);
    } else {
      doc.text(`${label}:`, margin, yPosition);
      yPosition += 5;
      doc.setFont(undefined, 'normal');
      doc.setTextColor(15, 23, 42);
      const lines = doc.splitTextToSize(String(value), pageWidth - 2 * margin - 10);
      doc.text(lines, margin + 5, yPosition);
      yPosition += lines.length * 5;
    }
    yPosition += 5;
  };

  // Start generating report
  addHeader();

  // Basic Information Section
  addSectionTitle('BASIC INFORMATION');
  
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(prisoner.fullName, margin, yPosition);
  yPosition += 8;
  
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(71, 85, 105);
  doc.text(`Case Number: ${prisoner.caseNumber}`, margin, yPosition);
  yPosition += 10;

  // Status badge
  const statusColors = {
    'Active': { bg: [34, 197, 94], text: 'Active' },
    'Released': { bg: [156, 163, 175], text: 'Released' },
    'Transferred': { bg: [251, 146, 60], text: 'Transferred' }
  };
  const statusColor = statusColors[prisoner.status] || statusColors['Active'];
  
  doc.setFillColor(...statusColor.bg);
  doc.roundedRect(margin, yPosition, 30, 6, 1, 1, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(statusColor.text, margin + 15, yPosition + 4, { align: 'center' });
  yPosition += 15;

  doc.setTextColor(15, 23, 42);
  
  // Personal Details in two columns
  const colWidth = (pageWidth - 2 * margin) / 2;
  let leftY = yPosition;
  let rightY = yPosition;

  // Left column
  doc.setFontSize(9);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('NIC Number:', margin, leftY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(prisoner.nic, margin + 30, leftY);
  leftY += 6;

  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Gender:', margin, leftY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(prisoner.gender, margin + 30, leftY);
  leftY += 6;

  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Date of Birth:', margin, leftY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(formatDate(prisoner.birthday), margin + 30, leftY);
  leftY += 6;

  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Age:', margin, leftY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(`${calculateAge(prisoner.birthday)} years`, margin + 30, leftY);
  leftY += 6;

  // Right column
  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Nationality:', pageWidth / 2, rightY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(prisoner.nationality, pageWidth / 2 + 30, rightY);
  rightY += 6;

  doc.setFont(undefined, 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Cell Number:', pageWidth / 2, rightY);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(15, 23, 42);
  doc.text(prisoner.cellNumber || 'Not Assigned', pageWidth / 2 + 30, rightY);
  rightY += 6;

  yPosition = Math.max(leftY, rightY) + 10;

  // Admission Information
  addSectionTitle('ADMISSION INFORMATION');
  addField('Admission Date', formatDate(prisoner.admissionDate), true);
  addField('Expected Release Date', formatDate(prisoner.expectedReleaseDate), true);
  if (prisoner.actualReleaseDate) {
    addField('Actual Release Date', formatDate(prisoner.actualReleaseDate), true);
  }

  // Prison Information
  addSectionTitle('PRISON INFORMATION');
  addField('Prison Name', prisoner.prison?.prisonName || 'N/A', true);
  addField('Location', prisoner.prison?.location || 'N/A', true);
  addField('Address', prisoner.prison?.address || 'N/A', false);

  // Additional Information
  if (prisoner.socialStatus) {
    addSectionTitle('ADDITIONAL INFORMATION');
    addField('Social Status', prisoner.socialStatus, false);
  }

  // Body Marks
  if (prisoner.bodyMarks && prisoner.bodyMarks.length > 0) {
    checkPageBreak(40);
    addSectionTitle('IDENTIFYING BODY MARKS');
    
    const bodyMarksData = prisoner.bodyMarks.map(mark => [
      mark.location,
      mark.description
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Location', 'Description']],
      body: bodyMarksData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    yPosition = doc.lastAutoTable.finalY + 10;
  }

  // Family Members
  if (prisoner.familyDetails && prisoner.familyDetails.length > 0) {
    checkPageBreak(40);
    addSectionTitle('FAMILY MEMBERS & CONTACTS');
    
    const familyData = prisoner.familyDetails.map(member => [
      member.memberName,
      member.relationship,
      member.nic,
      member.contactNumber,
      member.emergencyContact ? 'Yes' : 'No'
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Name', 'Relationship', 'NIC', 'Contact', 'Emergency']],
      body: familyData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    yPosition = doc.lastAutoTable.finalY + 10;
  }

  // Work Records
  if (workRecords.length > 0) {
    checkPageBreak(40);
    addSectionTitle('WORK RECORDS');
    
    if (workSummary) {
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text(`Total Hours: ${workSummary.totalHours} | Total Earned: ${formatCurrency(workSummary.totalEarned)} | Pending: ${formatCurrency(workSummary.totalPending)}`, margin, yPosition);
      yPosition += 8;
    }

    const workData = workRecords.slice(0, 20).map(record => [
      formatDate(record.workDate),
      record.taskDescription,
      `${record.hoursWorked}h`,
      formatCurrency(record.paymentAmount),
      record.paymentStatus,
      record.paymentDate ? formatDate(record.paymentDate) : 'N/A'
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Date', 'Task', 'Hours', 'Amount', 'Status', 'Paid Date']],
      body: workData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    yPosition = doc.lastAutoTable.finalY + 10;
    
    if (workRecords.length > 20) {
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(`Showing 20 of ${workRecords.length} records`, margin, yPosition);
      yPosition += 8;
    }
  }

  // Behavior Records
  if (behaviorRecords.length > 0) {
    checkPageBreak(40);
    addSectionTitle('BEHAVIOR RECORDS');
    
    if (behaviorSummary) {
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text(
        `Total: ${behaviorSummary.totalRecords} | Positive: ${behaviorSummary.positiveCount} | Negative: ${behaviorSummary.negativeCount} | Net Adjustment: ${behaviorSummary.approvedAdjustment} days`,
        margin,
        yPosition
      );
      yPosition += 8;
    }

    const behaviorData = behaviorRecords.slice(0, 15).map(record => [
      formatDate(record.incidentDate),
      record.behaviourType,
      record.severityLevel,
      record.description.substring(0, 50) + (record.description.length > 50 ? '...' : ''),
      `${record.sentenceAdjustmentDays > 0 ? '+' : ''}${record.sentenceAdjustmentDays}d`,
      record.adjustmentStatus
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Date', 'Type', 'Severity', 'Description', 'Adjustment', 'Status']],
      body: behaviorData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    yPosition = doc.lastAutoTable.finalY + 10;
    
    if (behaviorRecords.length > 15) {
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(`Showing 15 of ${behaviorRecords.length} records`, margin, yPosition);
      yPosition += 8;
    }
  }

  // Visit Records
  if (visits.length > 0) {
    checkPageBreak(40);
    addSectionTitle('VISIT HISTORY');
    
    if (visitsSummary) {
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text(
        `Scheduled: ${visitsSummary.scheduled} | Completed: ${visitsSummary.completed} | Cancelled: ${visitsSummary.cancelled}`,
        margin,
        yPosition
      );
      yPosition += 8;
    }

    const visitData = visits.slice(0, 15).map(visit => [
      formatDate(visit.visitDate),
      visit.visitor.visitorName,
      visit.relationship,
      `${formatTime(visit.visitTimeStart)} - ${formatTime(visit.visitTimeEnd)}`,
      visit.status,
      visit.purpose.substring(0, 40) + (visit.purpose.length > 40 ? '...' : '')
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [['Date', 'Visitor', 'Relation', 'Time', 'Status', 'Purpose']],
      body: visitData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: [30, 41, 59], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    yPosition = doc.lastAutoTable.finalY + 10;
    
    if (visits.length > 15) {
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(`Showing 15 of ${visits.length} records`, margin, yPosition);
      yPosition += 8;
    }
  }

  // Add footer to all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(i);
  }

  // Save the PDF
  const fileName = `Prisoner_Report_${prisoner.caseNumber}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
  
  return fileName;
};